"""empty message

Revision ID: bdbf3d298a43
Revises: 0fa8ef06b2d0
Create Date: 2016-01-23 14:59:41.564068

"""

# revision identifiers, used by Alembic.
revision = 'bdbf3d298a43'
down_revision = '0fa8ef06b2d0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'inner_ip',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.drop_index('ix_server_inner_ip', table_name='server')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_server_inner_ip', 'server', ['inner_ip'], unique=False)
    op.alter_column('server', 'inner_ip',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    ### end Alembic commands ###
